### ISSUE TITLE
tests for the old value feature

### ISSUE THREAD

**Issue by leoppro** [pingcap/ticdc#1039]
## Test Request

The old value feature (#708) is already development completed. We'll be testing this feature around correctness, stability and performance later. This issue focuses on the correctness test.

#### Correntness test program

Just as kafka_consumer, we need a customized program for the test of old value. We call it as `old-value-tester` in this issue.

`old-value-tester` should implement the following logic:
1. implement the Sink interface, have the capability of receiving the `RowChangedEvent`
2. after receiving a `RowChangedEvent`, check if the old value in the `RowChangedEvent` is equal with the row stored in the downstream database.
3. write the new row into the downstream database.

We can assume that the old value feature is correct if all the check were passed. the `old-value-tester` can be used in integration tests and UTF tests, etc.

#### TODO List

- [x] implement `old-value-tester`
- [x] port the current integration test with `old-value-tester` for old value
- [ ] design the test cases of UTF for old value feature
- [x] implement the test cases designed by previous step

**Comment by amyangfei** [comment]
solved in #1058
