### ISSUE TITLE
Logical flashback overall task tracking

### ISSUE THREAD

**Issue by amyangfei** [pingcap/ticdc#1057]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Based on the [Design document](https://github.com/pingcap/ticdc/files/5491515/Proposal_.Support.flashback.table.to.specific.TSO.pdf) and [Implement document](https://github.com/pingcap/ticdc/files/5491516/Implement.details.of.logical.flashback.table.pdf), we are going to implement the logical flashback feature. This issue is the task tracking for development.

**Describe the feature you'd like:**

Note: This feature is delayed

~~start: 2020-11-06
end: 2020-12-02~~

- [x] Parser support | 1 man-day https://github.com/amyangfei/parser/tree/support-flashback-tso
- [ ] TiDB executor support | 2 man-day
- [ ] Undo data generator, TiKV changelog collector (TiCDC refactor included) | 5 man-day
- [ ] Undo data generator, sort and decode module (TiCDC refactor included) | 5 man-day
- [ ] Undo sql generator | 2 man-day
- [ ] Overall debug and functional test | 3 man-day

**Describe alternatives you've considered:**

Some optional tasks

- New incremental scan API in TiKV
- Status query
- Undo executor performance optimization

**Comment by amyangfei** [comment]
won't do
