### ISSUE TITLE
kv client optimization

### ISSUE THREAD

**Issue by amyangfei** [pingcap/ticdc#1393]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently TiCDC subscribes to the KV changed logs based on region, and allocates an independent goroutine for each region to handle KV changed logs. When the region count is large, there exists huge lock contention in Golang runtime and CPU cost is too high, which will reduce replication performance.  Since the stability and performance of kv client have a great impact on TiCDC service, we want to refactor the implement mechanism of kv client in TiCDC, in order to increase stability and performance.

**Describe the feature you'd like:**

- [x] Implement a better way to handle region’s kv changed logs. #1397, #1439
- [x] Separate lock resolve logic from each region. #1397, #1426
- [x] Add batch mechanism to region event feeds dispatcher. #1720
- [x] Add more unit tests for kv client, ref: #1292 
- [x] Add benchmark for kv client. #1448 
- [x] Real scenario benchmark with new kv client [ga matrix](https://docs.google.com/document/d/1PAbTvIdLVCItwvDTSGxNTSF4Jj5wmK1U37ST5uu0q44/edit#heading=h.wvfxqs3i10q6)
- [x] Support kv client reconnect when resolved ts in TiKV is blocked #1586 
    - [x] cherry pick reconnect logic of client v2 to 5.0

## New bugs found in 5.0 test

- [x] region range lock blocking issue #1599. Both in v1 and v2
- [x] performance bottleneck in error handling and lock resolver #1612. Both in v1 and v2
- [x] The CRTs must be greater than the resolvedTs, #1548 . v2 only
- [x] kv client may raise error when stream.Recv meets io.EOF in some scenarios. Both in v1 and v2. #1641
