### ISSUE TITLE
Multiple owner could co-exist when PD is not stable

### ISSUE THREAD

**Issue by amyangfei** [pingcap/ticdc#1533]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

Detail information is in [ONCALL-2649](https://internal.pingcap.net/jira/browse/ONCALL-2649#), internal only

part of the analysis

分析 owner 切换的过程

  1. 14:17:39.853， cdc-2 成为 owner

```
cdc-02-0315.log:[2021/03/15 14:17:39.853 +08:00] [INFO] [server.go:297] ["campaign owner successfully"] [capture-id=c6b37ac1-0220-4e2b-a9a7-484adb3f9807]
```

  2. 14:27:13.836， cdc-2 的 etcd session 断开
  3. 14:27:14.936， cdc-2 检测到自己的 owner key 被删除，这时候代码里会 cancel context，后续 owner 操作 **应该都中止掉**

```
cdc-02-0315.log:[2021/03/15 14:27:13.836 +08:00] [INFO] [capture.go:167] ["capture session done, capture suicide itself"] [capture-id=c6b37ac1-0220-4e2b-a9a7-484adb3f9807]
cdc-02-0315.log:[2021/03/15 14:27:14.936 +08:00] [WARN] [owner.go:1176] ["owner campaign key deleted"] [key=/tidb/cdc/owner/4c33781617e4dbfc]
```

  4. 14:27:15.535，cdc-1 在该时刻成为 owner

```
cdc-01-0315.log:[2021/03/15 14:27:15.535 +08:00] [INFO] [server.go:297] ["campaign owner successfully"] [capture-id=9ffab06a-0f0c-4c22-a3c3-46ac8636434c]
```

  5. 14:27:19.344, 14:27:24.849，cdc-1 在创建 changefeed 过程中忽略了表 10352，可以判定此时 etcd 中存在旧的 task status 包括表 10352

```
cdc-01-0315.log:[2021/03/15 14:27:19.344 +08:00] [INFO] [owner.go:345] ["ignore known table"] [tid=10352] [table=testdb.xxxxx_xxx_loanlist] [ts=423569543778009125]
cdc-01-0315.log:[2021/03/15 14:27:24.732 +08:00] [INFO] [owner.go:235] ["Find new changefeed"] [info="{\"sink-uri\":\"***\",\"opts\":{},\"create-time\":\"2020-12-23T15:09:28.725994451+08:00\",\"start-ts\":421712984464949249,\"target-ts\":0,\"admin-job-type\":2,\"sort-engine\":\"memory\",\"sort-dir\":\".\",\"config\":{\"case-sensitive\":true,\"enable-old-value\":true,\"force-replicate\":false,\"check-gc-safe-point\":true,\"filter\":{\"rules\":[\"testdb.xxxxx_xxx_loanlist\"],\"ignore-txn-start-ts\":null,\"ddl-allow-list\":null},\"mounter\":{\"worker-num\":16},\"sink\":{\"dispatchers\":null,\"protocol\":\"default\"},\"cyclic-replication\":{\"enable\":false,\"replica-id\":1,\"filter-replica-ids\":null,\"id-buckets\":0,\"sync-ddl\":true},\"scheduler\":{\"type\":\"table-number\",\"polling-time\":-1}},\"state\":\"normal\",\"history\":[1612445350769],\"error\":null,\"sync-point-enabled\":false,\"sync-point-interval\":600000000000,\"creator-version\":\"\"}"] [changefeed=changefeed-rts-ebpdb-ebp-loanlist] ["checkpoint ts"=423569537473445919]
cdc-01-0315.log:[2021/03/15 14:27:24.849 +08:00] [INFO] [owner.go:345] ["ignore known table"] [tid=10352] [table=testdb.xxxxx_xxx_loanlist] [ts=423569544040153133]
```

  6. 14:27:19.008-14:27:30.790，cdc-2 还在进行 owner 操作

```
cdc-02-0315.log:[2021/03/15 14:27:19.008 +08:00] [INFO] [owner.go:1458] ["delete capture"] [capture-id=c6b37ac1-0220-4e2b-a9a7-484adb3f9807] [capture=203.3.219.14:8300]
cdc-02-0315.log:[2021/03/15 14:27:30.790 +08:00] [WARN] [owner.go:178] ["task status not found"] [capture-id=c6b37ac1-0220-4e2b-a9a7-484adb3f9807] [changefeed=changefeed-cdsafsdacas]
```

  7. 14:31:05.514 cdc-2 的 owner 才完全退出

```
cdc-02-0315.log:[2021/03/15 14:31:05.514 +08:00] [INFO] [server.go:307] ["owner exited"] [capture-id=c6b37ac1-0220-4e2b-a9a7-484adb3f9807]
cdc-02-0315.log:[2021/03/15 14:31:05.528 +08:00] [INFO] [server.go:261] ["server recovered"] [capture-id=c6b37ac1-0220-4e2b-a9a7-484adb3f9807]
```

2. What did you expect to see?

3. What did you see instead?

   Some tables are not replicated, and some task status in etcd has no table

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        v4.0.11
        ```

    - TiCDC version (execute `cdc version`):

        ```
        v4.0.11
        ```

### TODO List
- [x] Bug fix, https://github.com/pingcap/ticdc/pull/1540
- [ ] Add more metrics

**Comment by amyangfei** [comment]
### TODO List
- [ ] Bug fix
- [ ] Add more metrics
