### ISSUE TITLE
Open TiCDC protocol

### ISSUE THREAD

**Issue by leoppro** [pingcap/ticdc#161]
# Open TiCDC protocol project

# Overview

- Design an open TiCDC protocol, make other applications easy to access TiCDC data.
- Support Kafka and Pulsar as downstream data-targets for TiCDC.

### Background

TiCDC(TiDB Change Data Capture) is a new distributed incremental replication tool for TiDB ecosystem. TiCDC is still in development, but it already works properly in the experimental environment. When the TiCDC cluster starts, an owner will be voted and other nodes are named processor. The processors pull change key-value logs from TiKV, assemble logs into transactions, output to downstream data-target.The owner watches the replication progress of processors and coordinates them to ensure the transaction order.

### Problem Statement

- The current design of TiCDC is for MySQL protocol downstream data-targets. It cannot accept any Non-MySQL protocol data-targets. It's hard to access TiCDC data for other applications.

# Success Criteria

- Under the premise of ensuring correctness, TiCDC can output to Kafka/Pulsar.
- Exist a library can consume Kafka/Pulsar and parse open TiCDC protocol.
- Guarantee transaction integrity of downstream data even the TiCDC cluster is broken.

# TODO list

- [x]  Design an open TiCDC protocol.
- [x]  Implement TiCDC output using open TiCDC protocol.
- [x]  Implement open TiCDC protocol parser library and consumer client.
- [x]  Support output data to Kafka.
- [ ]  Support output data to Pulsar.
- [ ]  Correctness and stability test.

## Difficulty
Easy

## Score
2100

## Mentor(s)
@leoppro 

## Recommended Skills

- Go language
- Kafka/Pulsar operation
- Basic understanding of TiKV

# References
[TiCDC distributed design(Chinese version)](https://docs.google.com/document/d/1XXMt2S5zl8hq5l9tKO0u5Rr5mee29lIO_gb91RHb-2E)

[TiCDC HA design(Chinese version)](https://docs.google.com/document/d/15ho9j3x1BzomI7lzL-ljV2tUu2zFLN5cGn--yBm1iGY)

[TiCDC github repo](https://github.com/pingcap/ticdc)
