### ISSUE TITLE
Solve the sink OOM problem

### ISSUE THREAD

**Issue by liuzix** [pingcap/ticdc#1675]
## Problem

The sink OOMs because it stores too many rows in memory.

## Tasks

- [ ] Design & implement basic components used for per-table memory consumption control #1673 
- [ ] Make use of the components mentioned above, i.e. modify the processor (and potentially the sink) to add flow accounting and controlling.
- [ ] Run tests to verify that the solution so far meets some agreed-upon boundary, i.e. that it works when there are no more than `n` tables.
- [ ] If we want to expand the boundary, we refine the solution to add more critical features such as global memory consumption accounting, etc.

**Comment by amyangfei** [comment]
Could you confirm whether this issue can be closed @liuzix ?
