### ISSUE TITLE
Task Tracker: CDC peer-to-peer communication of timestamps

### ISSUE THREAD

**Issue by liuzix** [pingcap/ticdc#2464]
- [ ] Implement gRPC server
- [ ] Implement gRPC client
- [ ] Joint testing of server and client
- [ ] Modify Owner
- [ ] Modify Processor
- [ ] Final testing

**Comment by asddongmen** [comment]
can we close this question now? @liuzix
