### ISSUE TITLE
Tracking issue for restructure tests

### ISSUE THREAD

**Issue by tisonkun** [pingcap/ticdc#2660]
This is somewhat a subtask of https://github.com/pingcap/tidb/issues/26022 that we make a decision that deprecating [pingcap/check](https://github.com/pingcap/check) and adopting [testify](https://github.com/stretchr/testify). Take a look at the tidb issue for more information.

After an offline discussion with @overvenus we think it is fine we make the same change on this repo and here is the tracking issue for the effort.

If you have any further concern, please comment below and I'll reply in days.

We first write down a task list and since I have no time to continue the actual work, let's kick off when there is a contributor ask for starting the subtasks.

## Join Forces

If you want to participant the movement, you can comment under this issue to acquire pkg or files to migrate. For example,

```
Hi @tisonkun, I'd like to migrate tests under `errno` pkg. Please create a subtask and assign to me.
```

... I will react in time and do the favor for you.

Also you can directly comment under any open issues below without assignee to require assignment.

You can take a look at https://github.com/pingcap/tidb/pull/26375 as an example to do the migration.

## Subtasks

* [ ] migrate test-infra to testify for `cdc` pkg
* [ ] migrate test-infra to testify for `cdc/entry` pkg
* [ ] migrate test-infra to testify for `cdc/kv` pkg
* [ ] migrate test-infra to testify for `cdc/model` pkg
* [ ] migrate test-infra to testify for `cdc/owner` pkg
* [ ] migrate test-infra to testify for `cdc/processor` pkg
* [ ] migrate test-infra to testify for `cdc/processor/pipeline` pkg
* [ ] migrate test-infra to testify for `cdc/puller` pkg
* [ ] migrate test-infra to testify for `cdc/puller/fronter` pkg
* [ ] migrate test-infra to testify for `cdc/puller/sorter` pkg
* [ ] migrate test-infra to testify for `cdc/sink` pkg
* [ ] migrate test-infra to testify for `cdc/sink/codec` pkg
* [ ] migrate test-infra to testify for `cdc/sink/common` pkg
* [ ] migrate test-infra to testify for `cdc/sink/dispatcher` pkg
* [ ] migrate test-infra to testify for `cdc/sink/producer/kafka` pkg
* [ ] migrate test-infra to testify for `cmd` pkg
* [ ] migrate test-infra to testify for `pkg/config` pkg
* [ ] migrate test-infra to testify for `pkg/context` pkg
* [ ] migrate test-infra to testify for `pkg/cyclic` pkg
* [ ] migrate test-infra to testify for `pkg/cyclic/mark` pkg
* [ ] migrate test-infra to testify for `pkg/errors` pkg
* [ ] migrate test-infra to testify for `pkg/etcd` pkg
* [ ] migrate test-infra to testify for `pkg/filter` pkg
* [ ] migrate test-infra to testify for `pkg/flags` pkg
* [ ] migrate test-infra to testify for `pkg/hash` pkg
* [ ] migrate test-infra to testify for `pkg/httputil` pkg
* [ ] migrate test-infra to testify for `pkg/logutil` pkg
* [ ] migrate test-infra to testify for `pkg/notify` pkg
* [ ] migrate test-infra to testify for `pkg/orchestrator` pkg
* [ ] migrate test-infra to testify for `pkg/orchestrator/jsonstate` pkg
* [ ] migrate test-infra to testify for `pkg/orchestrator/util` pkg
* [ ] migrate test-infra to testify for `pkg/pipeline` pkg
* [ ] migrate test-infra to testify for `pkg/quotes` pkg
* [ ] migrate test-infra to testify for `pkg/regionspan` pkg
* [ ] migrate test-infra to testify for `pkg/retry` pkg
* [ ] migrate test-infra to testify for `pkg/scheduler` pkg
* [ ] migrate test-infra to testify for `pkg/types` pkg
* [ ] migrate test-infra to testify for `pkg/util` pkg
* [ ] migrate test-infra to testify for `pkg/version` pkg
* [ ] migrate test-infra to testify for `pkg/workerpool` pkg

**Comment by hi-rustin** [comment]
Duplicate of #2164

**Comment by tisonkun** [comment]
@hi-rustin thanks for spotting out, let's continue discussion there.
