### ISSUE TITLE
Tracking issue for sink interface refactor

### ISSUE THREAD

**Issue by overvenus** [pingcap/ticdc#3545]
In the current implementation (11/20/2021), when a table flushes its' sink, sink may return a checkpoint that is larger than resolved ts.
It can easily be reproduced when tables in a "slow" TiCDC node, whose checkpoint is **_Tca_**, are scheduled to a "faster" TiCDC node, whose checkpoint is **_Tcb_**, and **_Tca_** < **_Tcb_** .

Combine with #3029 and #2617, it can easily cause data lose and changefeed stuck when a "slow" is killed, e.g.,

- [ ] https://github.com/pingcap/ticdc/issues/3531
- [ ] https://github.com/pingcap/ticdc/issues/3521
- [ ] https://github.com/pingcap/ticdc/issues/3503

**Comment by overvenus** [comment]
Change to severity/moderate, as most issues are fixed.

**Comment by asddongmen** [comment]
@overvenus I think we can close this issue as a result of all the fix PR have been merge.
