### ISSUE TITLE
Tracking Issues and Feature for Correctness and Stability

### ISSUE THREAD

**Issue by maxshuang** [pingcap/ticdc#3844]
## Correctness

- ResolvedTs/CheckpointTs Management
    - Add Ts Tracking log for Error Troubleshooting
        - [ ] #3841
    - Need a better Ts managerment scheme 
        - [ ] #3842
 
- Scheduler
    - Sink double write 
        - [ ] [TODO] add issue link
    - Table lose
        - [ ] #3607
    - [TODO] Add Chaos test cases for Scheduler

- Data Parsing
    - [ ] #3644
    - [ ] #3843

- DDL & DML
    - [ ] [TODO] Online DDL test-infra cases

- Data verification scheme
    - [ ] [TODO] need  a module level data verification scheme

## Stability

- Scheduler
    - HA scenarios
        - Capture/KvNode network isolation  
            - [ ] #3616
    - Load balance  
        - [ ] #3654
    - Owner stuck in abnormal scenarios 
        - [ ] #3615

- Changefeeds Management
    - [ ] need test 100~200 changefeeds scenarios

- Upgrade/Downgrade Compatibility
    - Changefeed state compatibility 
        - [ ] #3473

### Describe the feature you'd like

above
