### ISSUE TITLE
Tracking issues for migrating integration tests

### ISSUE THREAD

**Issue by CharlesCheung96** [pingcap/ticdc#442]
## P0 
- [ ] Migrate the integration test framework

## P1
- [ ] api_v2
- [ ] autorandom
- [ ] availability
- [ ] avro_basic
- [ ] bank
- [ ] batch_add_table
- [ ] batch_update_to_no_batch
- [ ] bdr_mode
- [ ] canal_json_adapter_compatibility
- [ ] canal_json_basic
- [ ] canal_json_claim_check
- [ ] canal_json_content_compatible
- [ ] canal_json_handle_key_only
- [ ] canal_json_storage_basic
- [ ] canal_json_storage_partition_table
- [ ] cdc
- [ ] cdc_server_tips
- [ ] changefeed_finish
- [ ] changefeed_pause_resume
- [ ] changefeed_reconstruct
- [ ] charset_gbk
- [ ] ci_collation_compatibility
- [ ] cli_tls_with_auth
- [ ] cli_with_auth
- [ ] clustered_index
- [ ] common_1
- [ ] consistent_replicate_nfs
- [ ] csv_storage_basic
- [ ] csv_storage_multi_tables_ddl
- [ ] csv_storage_partition_table
- [ ] csv_storage_update_pk_clustered
- [ ] csv_storage_update_pk_nonclustered
- [ ] ddl_attributes
- [ ] ddl_puller_lag
- [ ] ddl_reentrant
- [ ] ddl_sequence
- [ ] debezium
- [ ] default_value
- [ ] drop_many_tables
- [ ] force_replicate_table
- [ ] foreign_key
- [ ] generate_column
- [ ] http_api
- [ ] http_api_tls
- [ ] http_api_tls_with_user_auth
- [ ] http_proxies
- [ ] kafka_big_messages
- [ ] kafka_big_messages_v2
- [ ] kafka_column_selector
- [ ] kafka_column_selector_avro
- [ ] kafka_compression
- [ ] kafka_messages
- [ ] kafka_simple_basic
- [ ] kafka_simple_basic_avro
- [ ] kafka_simple_claim_check
- [ ] kafka_simple_claim_check_avro
- [ ] kafka_simple_handle_key_only
- [ ] kafka_simple_handle_key_only_avro
- [ ] lossy_ddl
- [ ] many_pk_or_uk
- [ ] move_table
- [ ] mq_sink_dispatcher
- [ ] multi_capture
- [ ] multi_cdc_cluster
- [ ] multi_rocks
- [ ] multi_source
- [ ] multi_tables_ddl
- [ ] multi_tables_ddl_v2
- [ ] multi_topics
- [ ] multi_topics_v2
- [ ] new_ci_collation
- [ ] open_protocol_claim_check
- [ ] open_protocol_handle_key_only
- [ ] partition_table
- [ ] README.md
- [ ] region_merge
- [ ] resolve_lock
- [ ] resourcecontrol
- [ ] row_format
- [ ] run_group.sh
- [ ] run.sh
- [ ] safe_mode
- [ ] savepoint
- [ ] sequence
- [ ] server_config_compatibility
- [ ] simple
- [ ] split_region
- [ ] sql_mode
- [ ] storage_cleanup
- [ ] storage_csv_update
- [ ] tidb_mysql_test
- [ ] tiflash
- [ ] util
- [ ] _utils
- [ ] vector

## P3(With failpoint enabled, total 33)
- [ ] availability/owner.sh
- [ ] capture_session_done_during_task
- [ ] capture_suicide_while_balance_table
- [ ] changefeed_auto_stop
- [ ] changefeed_dup_error_restart
- [ ] changefeed_error
- [ ] changefeed_fast_fail
- [ ] changefeed_resume_with_checkpoint_ts
- [ ] consistent_partition_table
- [ ] consistent_replicate_ddl
- [ ] consistent_replicate_gbk
- [ ] consistent_replicate_storage_file
- [ ] consistent_replicate_storage_file_large_value
- [ ] consistent_replicate_storage_s3
- [ ] ddl_manager
- [ ] ddl_only_block_related_table
- [ ] event_filter
- [ ] gc_safepoint
- [ ] kafka_sink_error_resume
- [ ] kill_owner_with_ddl
- [ ] kv_client_stream_reconnect
- [ ] mq_sink_lost_callback
- [ ] owner_remove_table_error
- [ ] owner_resign
- [ ] processor_err_chan
- [ ] processor_etcd_worker_delay
- [ ] processor_resolved_ts_fallback
- [ ] processor_stop_delay
- [ ] sink_hang
- [ ] sink_retry
- [ ] synced_status
- [ ] synced_status_with_redo
- [ ] syncpoint

**Comment by asddongmen** [comment]
Total tasks:     137
Completed tasks: 39
Completion rate: 28.5%

**Comment by asddongmen** [comment]
-----------Total Summary-------------
Task Completion Statistics: 2025-01-14

Total tasks:     140
Completed tasks: 76
Completion rate: 54.3%

**Comment by asddongmen** [comment]
-----------Total Summary-------------
Task Completion Statistics: 2025-01-17

Total tasks: 140
Completed tasks: 86
Completion rate: 61.4%

**Comment by wk989898** [comment]
-----------Total Summary-------------
Task Completion Statistics: 2025-03-04

Total tasks: 142
Completed tasks: 112
Completion rate: 78.9%
