### ISSUE TITLE
Support open protocol data store and consume in cloud storage

### ISSUE THREAD

**Issue by amyangfei** [pingcap/ticdc#655]
## Feature Request

**Is your feature request related to a problem? Please describe:**

TiCDC provides MySQL sink and Kafka sink now, which can replicate data to MySQL compatible database and Kafka respectively. Some usage scenarios still need to send the changed events to some low-cost storage medium such as S3, in order to keep data for a long time and can consume historical changed events asynchronously. 

**TODO list**

-  [ ] As we have defined a [`Sink` interface](https://github.com/pingcap/ticdc/blob/85fd7eae09a9ecbace9c3ebce1de0e197c3b7224/cdc/sink/sink.go#L36), it is recommended to implement a new sink to send changed data to cloud storage, in the current stage we tend to implement an S3 sink first.
- [ ] Since a changefeed could be distributed in multiple captures, we should make a rule about how data is stored in the storage system, and take the following points into consideration:
   - [ ] We can consume the data with some consistency level guarantee according to different data storage distribution, basically we should provide row-level guarantee or table-level guarantee at least. 
   - [ ] Maybe we should store some meta data to enable consume data from one `tso` to another `tso`, without too much data scan.
- [ ] Besides S3 sink, we should also design the consumption strategies based on the storage sketch in cloud storage.

**Describe alternatives you've considered:**

Besides S3, we could support other cloud storage provides, such as Azure, GCS, etc. But in all these cases we need to implement more new code.

**Teachability, Documentation, Adoption, Migration Strategy:**

### Value description 

This feature enriches the usage scenario in cloud environment.

### Value score 

* (TBD) / 5

### Workload estimation 

* (TBD) person-day

**Comment by amyangfei** [comment]
This feature will be delivered in PiTR
