### ISSUE TITLE
Support Avro sink and make TiCDC compatible with Kafka connect

### ISSUE THREAD

**Issue by amyangfei** [pingcap/ticdc#660]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Apache Kafka provides flexible connectors mechanism, and there exist a lot of third-party connectors implementation which can receive changed logs from upstream in the [Avro](https://avro.apache.org/) protocol, send data to Kafka via `source connector`, and the data in Kafka can be consumed by `sink connector` and replicated to downstream. 

**TODO list**

- [x] Support writing Avro encoded Kafka Connector-compatible data when writing to Kafka.
- [x] Support replicating Avro schema to an open-source `Schema Registry`, such as [Confluent Schema Registry for Kafka](https://github.com/confluentinc/schema-registry)
- [x] Provide a full solution for data replication link, TiDB -> TiCDC -> Kafka -> TiDB, with Avro data from TiCDC to Kafka and using `Kafka sink connector` to consume data from Kafka to TiDB.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

- [TiCDC Avro support research](https://docs.google.com/document/d/1uoJAOiFQTZdEb3jrvqa-B-TAWPrK7PnyqmqrRgEpYKI/edit)

### Value description 

This is an important feature in third-party ecosystem

### Value score 

* (TBD) / 5

### Workload estimation 

* 30 person-day, still need 15 person-day from 7-28

### Time

GanttStart: 2020-07-15
GanttDue: 2020-08-31
GanttProgress: 90%

**Comment by abbccdda** [comment]
Is this still open?

**Comment by scsldb** [comment]
Reason for reprioritization: development complete, testing in process, more important development tasks at the moment.

**Comment by amyangfei** [comment]
- Integration test has been added in https://github.com/pingcap/ticdc/issues/1039
- More test about protocol is still in discussion
